In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
#importing dataset
banknote_df = pd.read_csv("https://raw.githubusercontent.com/Sanchitbhadani-1/Dimensionality-Reduction/refs/heads/main/Learning%20PCA%20and%20LDA/banknote(in).csv")
#displaying dataset header
banknote_df.head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [ ]:
# dividing data into features and labels
X = banknote_df.drop(["class"], axis = 1)
y = banknote_df.filter(["class"], axis = 1)

In [ ]:
#dividing data into 80-20% training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.20, random_state=0)

In [ ]:
#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#importing PCA class
from sklearn.decomposition import PCA
#creating object of the PCA class
pca = PCA()
#training PCA model on training data
X_train = pca.fit_transform(X_train)
#making predictions on test data
X_test = pca.transform(X_test)

In [ ]:
#printing variance ratios
variance_ratios = pca.explained_variance_ratio_
print(variance_ratios)

[1.]

In [ ]:
#use two principal components
from sklearn.decomposition import PCA
# The 'X_train' data currently has only 1 feature due to the previous PCA step (in cell OWOegn0Vdwpa).
# Therefore, n_components can at most be 1.
# If you intended to have 2 components, you should specify n_components=2 in the initial PCA call.
pca = PCA(n_components=1) # Changed from 2 to 1 to resolve the ValueError
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [ ]:
#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression ( )
lg.fit ( X_train , y_train )
# Predicting the Test set results
y_pred = lg.predict ( X_test )
#evaluating results
from sklearn.metrics import accuracy_score
print ( accuracy_score ( y_test , y_pred ) )
# 0.8666666666666667

0.9890909090909091

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
#importing LDA class
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
#creating object of the LDA class
lda = LDA()
#training LDA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
#printing variance ratios
variance_ratios = lda.explained_variance_ratio_
print(variance_ratios)
# Output: [1.]

[1.]

In [ ]:
#creating object of the LDA class
lda = LDA(n_components = 1)
#training PCA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression()
lg.fit(X_train, y_train)
# Predicting the Test set results
y_pred = lg.predict(X_test)
#evaluating results
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.9890909090909091

In [ ]:
churn_df = pd.read_csv("/content/drive/MyDrive/Data/customer_churn(in).csv")
churn_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
churn_df = churn_df.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [ ]:
X = churn_df.drop(['Exited'], axis=1)
y = churn_df['Exited']

In [ ]:
numerical = X.drop(['Geography', 'Gender'], axis = 1)
numerical.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,42,2,0.00,1,1,1,101348.88
1,608,41,1,83807.86,1,0,1,112542.58
2,502,42,8,159660.80,3,1,0,113931.57
3,699,39,1,0.00,2,0,0,93826.63
4,850,43,2,125510.82,1,1,1,79084.10

In [ ]:
categorical = X.filter(['Geography', 'Gender'])
categorical.head()

  Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
4     Spain  Female

In [ ]:
cat_numerical = pd.get_dummies(categorical,drop_first=True)
cat_numerical.head()

   Geography_Germany  Geography_Spain  Gender_Male
0              False            False        False
1              False             True        False
2              False            False        False
3              False            False        False
4              False             True        False

In [ ]:
X = pd.concat([numerical, cat_numerical], axis = 1)
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False

In [ ]:
#dividing data into 80-20% training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.20, random_state=0)

In [ ]:
#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#importing PCA class
from sklearn.decomposition import PCA
#creating object of the PCA class
pca = PCA()
#training PCA model on training data
X_train = pca.fit_transform(X_train)
#making predictions on test data
X_test = pca.transform(X_test)

In [ ]:
#printing variance ratios
variance_ratios = pca.explained_variance_ratio_
print(variance_ratios)

[0.15034639 0.1028392  0.09996458 0.09293917 0.09151456 0.09055952
 0.08971894 0.08848339 0.08157563 0.06903591 0.04302272]

In [ ]:
#use two principal components
from sklearn.decomposition import PCA
# The 'X_train' data currently has only 1 feature due to the previous PCA step (in cell OWOegn0Vdwpa).
# Therefore, n_components can at most be 1.
# If you intended to have 2 components, you should specify n_components=2 in the initial PCA call.
pca = PCA(n_components=1) # Changed from 2 to 1 to resolve the ValueError
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [ ]:
#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression ( )
lg.fit ( X_train , y_train )
# Predicting the Test set results
y_pred = lg.predict ( X_test )
#evaluating results
from sklearn.metrics import accuracy_score
print ( accuracy_score ( y_test , y_pred ) )
# 0.8666666666666667

0.7975

In [ ]:
#importing LDA class
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
#creating object of the LDA class
lda = LDA()
#training LDA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

In [ ]:
#printing variance ratios
variance_ratios = lda.explained_variance_ratio_
print(variance_ratios)
# Output: [1.]

[1.]

In [ ]:
#creating object of the LDA class
lda = LDA(n_components = 1)
#training PCA model on training data
X_train = lda.fit_transform(X_train, y_train)
#making predictions on test data
X_test = lda.transform(X_test)

In [ ]:
#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression
#training the logistic regression model
lg = LogisticRegression()
lg.fit(X_train, y_train)
# Predicting the Test set results
y_pred = lg.predict(X_test)
#evaluating results
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7975